apiVersion: v1
kind: Service
metadata:
  name: rabbitmq2
spec:
  ports:
    - port: 5671
      targetPort: 5671
      name: api1
    - port: 5672
      targetPort: 5672
      name: api2
    - port: 4369
      targetPort: 4369
      name: epmd
    - port: 25672
      targetPort: 25672
      name: erlang
    - port: 15672
      targetPort: 15672
      name: web
  selector:
    cluster-name: rabbitmq-cluster
    node: rabbitmq2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        node: rabbitmq2
        cluster-name: rabbitmq-cluster
    spec:
      containers:
      - image: 10.254.9.21/library/epic-rabbitmq-server:3.6.10
        name: rabbitmq2
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq/mnesia"
          name: mnesia
        ports:
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 25672
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
          name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: epic
        - name: RABBITMQ_DEFAULT_PASS
          value: epic1234
        - name: RABBITMQ_DEFAULT_VHOST
          value: epic-rabbitmq
        - name: CLUSTERED
          value: "true"
        - name: CLUSTER_WITH
          value: "rabbitmq1"
        - name: RABBITMQ_HOSTNAME
          value: "rabbitmq2"
      volumes:
      - name: mnesia
        hostPath:
          path: "/opt/data/rabbitmq2/mnesia"
---
